# Generated by Django 3.2.3 on 2021-05-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spotify_id', models.CharField(max_length=25)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dancibility', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('loudness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('speechiness', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tempo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valence', models.DecimalField(decimal_places=2, max_digits=7)),
                ('music_key', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('artist', models.ManyToManyField(to='dashboard.Artist')),
            ],
        ),
    ]
