# Generated by Django 3.2.3 on 2021-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='acousticness',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='dancibility',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='loudness',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='speechiness',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
