# Generated by Django 3.2.3 on 2021-05-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210520_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='dancibility',
            new_name='danceability',
        ),
    ]
