# Generated by Django 3.2.3 on 2021-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_track_liveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
